= Developers Connected API
:toc:
:toclevels: 5

== Running the tests

NOTE: Base location is assumed to be the project directory.

To run API tests it is only required to execute the next command:

[source,bash]
sbt test

== Running the API

NOTE: Base location is assumed to be the project directory.

To run the API it is required to follow next steps:

. Package the API in a Docker container running:
+
[source,bash]
sbt docker:publishLocal

. Move to `dc` directory:
[source,bash]
cd dc

. Create an `.env` file with following structure:
+
[source]
GITHUB_TOKEN=<your-github-token>
TWITTER_TOKEN=<your-twitter-token>
+
Please, remember to **REPLACE** the default values.

. Get the environment up with:
[source,bash]
docker-compose up -d

That's it! Your API should be running, and the logs should be getting injected into the Elasticsearch via Logstash to be searched via Kibana.

NOTE: Kibana can be accessed at http://localhost:5601

== Requesting the API

It is possible to perform requests to the API using the `Postman` collection and environment present at `postman/` directory, it is only required to import them both.

Requests can also be performed via `curl`:

[source,bash]
curl http://localhost:8080/developers/connected/dev1/dev2

== Examples

An example of connected developers is the trio `djspiewak`, `rossabaker` and `milessabin`:

[source,bash]
$ curl http://localhost:8080/developers/connected/djspiewak/rossabaker
{"organizations":["typelevel"],"connected":true}

[source,bash]
$ curl http://localhost:8080/developers/connected/djspiewak/milessabin
{"organizations":["typelevel"],"connected":true}

[source,bash]
$ curl http://localhost:8080/developers/connected/rossabaker/milessabin
{"organizations":["typelevel"],"connected":true}

An example of non-connected developers that share an organization in common is the pair `djspiewak` and `mpilquist`:

[source,bash]
$ curl http://localhost:8080/developers/connected/djspiewak/mpilquist
{"connected":false}

An example of non-connected developers that follow each other is the pair `djspiewak` and `odersky`:

[source,bash]
$ curl http://localhost:8080/developers/connected/djspiewak/odersky
{"connected":false}

And an example invalid developers is the pair `asdlfkhlas` and `qwoeripu`:

[source,bash]
$ curl http://localhost:8080/developers/connected/asdlfkhlas/qwoeripu
{"errors":["asdlfkhlas is not a valid user in github","qwoeripu is not a valid user in github","asdlfkhlas is not a valid user in twitter","qwoeripu is not a valid user in twitter"]}
